#pragma once

#define ERROR_FILE_NOT_FOUND 2
#define ERROR_NUMBER_WITH_LETTERS_IN_IT 3
#define ERROR_DECIMAL_WITH_LETTERS_OR_SECOND_POINTS_IN_IT 4
#define ERROR_MAX_LEXEME_SIZE_EXCEDED 5
#define ERROR_COMMENT_NOT_FORMATED_CORRECTLY 6
#define ERROR_SYNTAX_ERROR_NEAR 7
#define ERROR_SYNTAX_ERROR_VOID_PARAM 8


void errorColor();
void normalColor();
void marineColor();
void marine2Color();